[build]
  # Commande pour installer les dépendances
  command = "npm install && npm run build"
  
  # Dossier de sortie (généré par Next.js)
  publish = ".next"

[build.environment]
  # Version de Node.js
  NODE_VERSION = "18"
  
  # Variables d'environnement pour Next.js
  NEXT_TELEMETRY_DISABLED = "1"

# Redirections pour les routes Next.js
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Headers de sécurité
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

# Cache pour les assets statiques
[[headers]]
  for = "/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Cache pour les images
[[headers]]
  for = "/*.jpg"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "/*.jpeg"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "/*.png"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "/*.webp"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

# Configuration des fonctions serverless (pour les API routes)
[functions]
  # Dossier des fonctions (Next.js gère cela automatiquement)
  directory = ".next/serverless"
